# fly.toml app configuration file generated for reviewapi on 2023-09-05T12:21:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reviewapi"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
