POST http://127.0.0.1:5000/rate
content-type: application/json

{
    "reviews": ["You will know as soon as you take it out of the packaging that it is all about quality. No leaks, not drips. don't buy one buy two.", 
                "The nozzle is left hand thread. You will never get used to turning it the wrong way to shut it off. The metal part that you see is steel but, the part that breaks, that you don't see, is plastic. Too expensive to throw away so, I was glad that it finally broke. Never liked the left hand threads, drove me nuts.",
                "Love it, its the real deal not the cheap knockoff.",
                "Great Service and Product",
                "Best nozzle ever",
                "This is high quality with a wide range of water disbursement. Do yourself a favor, drop the cheap Walmart nozzle and buy this one!",
                "Liked it so much, this is the second one after having the same one for the year. It was dropped on the concrete floor  many times, no problem whatsoever.",
                "Works like a champ. Have very low water pressure.......results were like a low force power washer. Highly recommended.",
                "Great nozzle",
                "I liked this nozzle so much that I immediately order another one.  They work smoothly and leak-proof.",
                "I really like the settings nice and light weight told my mom she should get one and along with the DAP XHOSE PRO.",
                "Very nice nozzle.  I am surprised how well I like it.", 
                "excellent", 
                "Purchased this hose nozzle a while back to use each time I need to water my yard...LOVE IT!!!  The nozzle is big enough for what is supposed to be used for.  Several of my neighbors have asked me where did I get it.  This was a great purchase and I'm very happy with all the settings it comes with.",
                "Great product. Easy to hold. Durable as heck. Had one for 10 years and then it went missing. Now I have four of them.",
                "Weak flow and spray pattern changes itself from a broken spray to stream and damages plants!  Will not buy these again.",
                "excellent.",
                "So far so good.....",
                "Doesn't have enough patterns, especially gentle patterns to not disturb topsoil.  Would not recommend for gardening.  It's also a pain in the butt to turn on and off if you forget which end you're at, and also a pain to switch all the way over to get to the other end.  It may be sort of comfortable to hold, but there are also multi-patterned ergonomic nozzles out there.",
                "This is a super nozzle built well and long lasting if you don't leave it out in the snow",
                "Love these hose nozzles.  They are made out of the same materials as fire department hoses and do not break if they are dropped. I have four of them-- one for each spiggot.  One of mine developed a leak and the company's warranty policy is terrific if you need to call them.  I love the adjustable head with an off position in either direction. You can spray gardens from much farther away than you can with other nozzles.  I have seen people looking at hose nozzles in hardware and big box stores. I advise them to go to A azon and buy a Bonaire nozzle.  Looks like they make an awesome product for washing cars also.",
                "Great!  Use it to water my lawn.  Thanks!",
                "Great !",
                "Easy to twist and very durable. Perfect for watering my tomatoes.",
                "I really, really don't like this nozzle. I don't understand all the good reviews. There is no control except continual rotation of the large head, left to right or back, and if you have small hands or arthritis (I have both), this is a bother. I have a lot of flower beds all over my patio and I find myself keeping the hose on across the stone to avoid turning it on and off over and over again. While I don't live in an area with water shortages, it is still wasteful. I bought two of these, one for the front and one for the back yard. I will be giving both to Goodwill.",
                "Finally!  A hose nozzle that works and lasts!",
                "love it",
                "Pressure is awful!!! I get better pressure from just putting my thumb over the hose....",
                "Don't know if I got a one that was not assembled properly or they all do this. The one I got would not adjust either way to a nice shower type flow.<br />It would go from off to a mist then to almost full power spray and back down but would not adjust to a shower type flow like you would rinse your car off. I am returning it.",
                "Works really well!!!",
                "Stopped working properly on the fourth use. I disassembled the nozzle and found that the rubber o-ring had dislodged and clogged the outlet. I reseated the o-ring back in its proper position, however, even moderate water pressure causes it to dislodge once again.  We have very high water pressure in our area (&#62;200psi) so perhaps this was a contributing factor. However, our last oversized nozzle (Orbit) lasted over a year before it gave up the ghost, so I believe it's reasonable to expect more than four uses!"]
}